# -*- coding: utf-8 -*-
"""labwork1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13saR0bl1Oci5HOGy_eBg50AGX8kFyaq2
"""

#Ex1
radius = float(input('Enter circle radius: '))
area = 3.14 * (radius ** 2)

print(f'Circle area = {area}')

#Ex2
celsius = float(input('Enter the temperature in Celsius: '))
fahrenheit = (celsius * 9/5) + 32

print(f'{celsius} (C) = {fahrenheit} (F)')

#Ex3
n = int(input('Enter a number: '))

if n <= 1:
  is_prime = False
else:
  is_prime = True
  for i in range(2, n):
    if n % i == 0:
      is_prime = False
      break

if is_prime:
  print(f'{n} is a prime number')
else:
  print(f'{n} is NOT a prime number')

#Ex4
n = int(input('Enter a number: '))

if n <= 0:
  is_perfect = False
else:
  divisor = 0
  for i in range(1, n):
    if n % i == 0:
      divisor += i

  if divisor == n:
    is_perfect = True
  else:
    is_perfect = False

if is_perfect:
  print(f'{n} is a perfect number')
else:
  print(f'{n} is NOT a perfect number')

#Ex5
colors = ['Golden', 'Orange', 'Red', 'Grey', 'White']

user_input = input('What is your favourite color? ')
if user_input in colors:
  index = colors.index(user_input)
  print(f'Your color is at index {index} in my list')
else:
  print(f'Sorry, I could not find your color')

#Ex6
range1 = list(range(0, 7))
print('range1', range1)

range2 = list(range(1, 11, 3))
print('range2', range2)

range3 = list(range(5, 0, -1))
print('range3', range3)

range4 = list(range(6, -3, -2))
print('range4', range4)

#Ex7
def remove_dollar_sign(s):
  return s.replace('$', '')
user_input = input('Enter something w/ dollar sign: ')
print(remove_dollar_sign(user_input))

#Ex8
def extract_even(l):
  result = []
  for i in l:
    if i % 2 == 0:
      result.append(i)
  return result

l = [1, 4, 5, -1, 10]
print(extract_even(l))

#Ex9
def factorial(n):
  if n == 0 or n == 1:
    return 1
  return n * factorial(n-1)

user_input = int(input('Enter a number: '))
print(f'Factorial of {user_input} is {factorial(user_input)}')

#Ex10
def get_divisor(n):
  divisor = []
  for i in range(1, n + 1):
    if n % i == 0:
      divisor.append(i)
  return divisor

user_input = int(input('Enter a number: '))
print(f'Divisors of {user_input} are {get_divisor(user_input)}')

#Ex11
def distance(x1, y1, x2, y2):
    dx_squared = (x2 - x1) ** 2
    dy_squared = (y2 - y1) ** 2

    distance = (dx_squared + dy_squared) ** 0.5
    return distance

print(distance(1, 2, 4, 6))

#Ex12
m=int(input("Enter m="))
n=int(input("Enter n="))

for i in range(1,n+1):
    if (i==1 or i==n):
        for j in range(1,m+1):
            print("* ", end="")
        print("")
    else:
        print("* ",end="")
        for j in range(2,m):
            print("  ", end="")
        print("*")